config/routes.rb
Rails.application.routes.draw do
  resources :contact
  resources :product do
    collection { post :import }
  end
  resources :users
  resources :policy
  resources :about
  get '/manage-products', to: 'users#manage_products'
  root 'welcome#index'
  post '/sent', to: "contact#sent"

  # get :search, :action => 'search_product', :as => 'search_product'
  # get 'search/:q', :action => 'search', :as => 'search'
end

app/models/about.rb
class About < ActiveRecord::Base

end

app/models/contact.rb
class Contact < MailForm::Base
  def headers
    {
      :subject => "test",
      :to => "alexung.ucsb@gmail.com",
      :from => "alexung.ucsb@gmail.com"
    }
end

app/models/policy.rb
class Policy < ActiveRecord::Base

end

app/models/product.rb
class Product < ActiveRecord::Base
    validates_presence_of :name

    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|
        product = find_by_id(row["id"]) || new
        product.attributes = row.to_hash
        product.save!
      end
    end

    def self.search(search)
      # if search
      #   # binding.pry
      #   Product.find(['name LIKE ?', '%#{search}%'])
      # else
      #   Product.all
      # end
      where("name LIKE ?", "%#{search}%")
    end


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :username
  validates_uniqueness_of :username

  def self.authenticate(username, password)
    user = find_by(username: username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
      @q = Product.ransack(params[:q])
      @product = @q.result.paginate(:page => params[:page], :per_page => 9)
      @products = Product.uniq.pluck(:category)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  require 'mail'
  protect_from_forgery

  def index
    # mail = Mail.new do
    #   to "alexung.ucsb@gmail.com"
    # end

    # mail['from'] = 'alexung.ucsb@gmail.com'
    # mail.subject = 'This is a test email'
    # mail.body = 'lolololololol'

    # mail.header['X-Custom-Header'] = 'custom value'

    # mail.to_s
    UserMailer.welcome_email().deliver_now!
    @q = Product.ransack(params[:q])
    @product = @q.result.paginate(:page => params[:page], :per_page => 9)

  end

  def sent
    # mail = Mail.new do
    #   to "alexung.ucsb@gmail.com"
    # end

    # mail['from'] = 'alexung.ucsb@gmail.com'
    # mail.subject = 'This is a test email'
    # mail.body = 'lolololololol'

    # mail.header['X-Custom-Header'] = 'custom value'

    # mail.to_s
      UserMailer.welcome_email().deliver_now!

      # format.html { redirect_to('alexung.ucsb@gmail.com', notice: 'Email successfully sent.') }
      # format.json { render json: 'alexung.ucsb@gmail.com', status: :created, location: 'alexung.ucsb@gmail.com'}
  end

end

app/controllers/policy_controller.rb
class PolicyController < ApplicationController
  def index
      @q = Product.ransack(params[:q])
      @product = @q.result.paginate(:page => params[:page], :per_page => 9)
      @products = Product.uniq.pluck(:category)
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
      @q = Product.ransack(params[:q])
      @product = @q.result.paginate(:page => params[:page], :per_page => 9)
  end

  def show
    @items = []
    @products = Product.search(params[:search])
    @products.each do |product|
      @items.push(Product.find(product.id))
    end
    @product = Product.paginate(:page => params[:page], :per_page => 9)

  end

  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Products Imported."
  end

  def product_params
    params.require(:product).permit(:name, :image, :price, :order_number)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to manage_products_path, notice: "Signed up!"
    else
      render "new"
    end
  end

  def manage_products
    @user = User.find(1)
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
      @q = Product.ransack(params[:q])
      @product = @q.result.paginate(:page => params[:page], :per_page => 9)
      @products = Product.uniq.pluck(:category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>
<p>This is the about us page</p>

app/views/contact/index.html.erb
<h1>Contact Us</h1>
<form action="/sent" method="post">
  <input type="text" name="email" placeholder="Email"><br>
  <input type="text" name="title" placeholder="Message Subject"></br>
  <input type="text" name="message" placeholder="Type Message Here"><br>
  <input type="submit" value="Submit">
</form>

app/views/contact/sent.html.erb
<h1>Contact Us</h1>
<h3>Emails were sent!</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KingTools</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>
<body>
  <div class="custom-navbar navbar-default">
      <span class="site-title"><a href="/">King Tools & Equipment</a></span>
  <% if @q %>
    <%= search_form_for @q, url: product_index_path do |f| %>
      <span class="field">
        <%= f.label :name_cont, "Name contains" %>
        <%= f.text_field :name_cont %>
      </span>
      <span class="actions"><%= f.submit "Search"%></span>
    <% end %>
  <% end %>
  <a href="/product">Products</a>
  <a href="/contact">Contact Us</a>
 </div>

<%= yield %>

<script type="text/javascript" charset="utf-8">
    window._token = '<%= form_authenticity_token -%>';
</script>

</body>
</html>

app/views/policy/index.html.erb
<h1>Policy</h1>
<p>This is the policy</p>

app/views/product/index.html.erb
<div class="container">
  <h1>PRODUCTS</h1>
</div>

<div class="container">
  <% @product.each_slice(3) do |array_of_3_items| %>
    <div class="row">
      <% array_of_3_items.each do |item| %>
      <div class="col-md-4">
        <img src="<%= item.image %>" alt="Tool image" height="181" width="150"><br>
        <%= item.name %>
      </div>
      <% end %>
    </div>
  <% end %>

  <%= will_paginate @product %>


</div>

app/views/product/show.html.erb
<div class="container">
  <h1>PRODUCTS</h1>
</div>

<div class="container">
  <% @items.each_slice(3) do |array_of_3_items| %>
    <div class="row">
      <% array_of_3_items.each do |item| %>
      <div class="col-md-4">
        <img src="<%= item.image %>" alt="Tool image" height="181" width="150"><br>
        <%= item.name %>
      </div>
      <% end %>
    </div>
  <% end %>

  <%= will_paginate @product %>


</div>

app/views/users/manage_products.html.erb
<h2>Import products</h2>
<%= form_tag import_product_index_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for :user, url: users_path do |f| %>

<%= f.label :username %>
<%= f.text_field :username %><br><br>

<%= f.label :password %>
<%= f.password_field :password %><br><br>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %><br><br>

<%= f.submit "Create user, baby" %>

<% end %>

app/views/welcome/index.html.erb
<div id="wrapper">
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <% @products.each do |item| %>

      <li class="item-category">
        <a href="/product?utf8=✓&q%5Bname_cont%5D=<%=item%>&commit=Search">
          <%= item %>
        </a>
      </li>
      <% end %>
    </ul>
  </div>

  <div id="page-content-wrapper">
    <h1>HOMEPAGE</h1>

    <!-- test -->
    <div id="owl-lol" class="owl-carousel owl-theme">
      <div class="item"><img src="assets/tools.jpg" alt="Tool Image"></div>
      <div class="item"><img src="assets/tools2.jpg" alt="Tool Image"></div>
      <div class="item"><img src="assets/tools3.jpg" alt="Tool Image"></div>
      <div class="item"><img src="assets/tools4.jpg" alt="Tool Image"></div>
      <div class="item"><img src="assets/tools5.jpg" alt="Tool Image"></div>
      <div class="item"><img src="assets/tools6.jpg" alt="Tool Image"></div>
      <div class="item"><img src="assets/tools7.jpg" alt="Tool Image"></div>

    </div>
      <!-- end test -->

      <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a>

      <div class="container">
        <iframe width="100%" height="100%" frameborder="0" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&q=1255+E+Acacia+St,Ontario,CA,+91761" allowfullscreen></iframe>
      </div>
    <div class="container footer">
      <a href="/policy">Policy</a>
      <a href="/about">About Us</a>
    </div>
  </div>
</div>

  <script>
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
  });

    $("#owl-lol").owlCarousel();

  </script>